input_user =  '//*[@id="f_usuario"]'
input_pass ='//*[@id="f_senha"]'
login_confirm = '//*[@id="form1"]/div[4]/div[1]/button'
work_month_date_select = '//*[@id="a_competencia"]'
open_month_date_options =  '//*[@id="navbar"]/div/div/ul/li[2]/ul/li[3]/a'
open_select_month_date = '//*[@id="select2-chosen-10"]'
menu_tesouraria = '//*[@id="link_modulo_TES"]/span'
caixa_bancos = "/html/body/div[3]/div[1]/ul/li[8]/ul/li[2]/a"
new_debt_select_box = '//*[@id="mainContent"]/div[2]/div[2]/div/div[1]/div/div/div[1]/button/span[2]'
new_debt_select_element =  '//*[@id="mainContent"]/div[2]/div[2]/div/div[1]/div/div/div[1]/ul/li[3]/a'
new_group_debt_select_box = '//*[@id="mainContent"]/div[2]/div[2]/div/div[1]/div/div/div[1]/button/span[2]'
new_group_debt_select_element = '//*[@id="mainContent"]/div[2]/div[2]/div/div[1]/div/div/div[1]/ul/li[4]/a'
new_intern_trans_select_box = '//*[@id="mainContent"]/div[2]/div[2]/div/div[1]/div/div/div[1]/button/span[2]'
new_intern_trans_select_element = '//*[@id="mainContent"]/div[2]/div[2]/div/div[1]/div/div/div[1]/ul/li[6]/a'
new_receive_select_box = '//*[@id="mainContent"]/div[2]/div[2]/div/div[1]/div/div/div[1]/button/span[2]'
new_receive_select_element = '//*[@id="mainContent"]/div[2]/div[2]/div/div[1]/div/div/div[1]/ul/li[1]/a'